/**
 * @fileOverview Centralized UI strings for the ShuttleScore application.
 * This file serves as the single source of truth for all user-facing text,
 * enabling easy future translations.
 */

export const UI_STRINGS = {
  common: {
    appTitle: "ShuttleScore",
    recordAction: "Record Action",
    edit: "EDIT",
    saveChanges: "SAVE CHANGES",
    archivePerformance: "ARCHIVE PERFORMANCE",
    synchronizing: "SYNCHRONIZING...",
    archiving: "ARCHIVING...",
    loading: "Loading...",
    win: "WIN",
    loss: "LOSS",
    proWin: "PRO WIN",
    proLoss: "PRO LOSS",
    training: "Training",
    officialPerformance: "Official Performance",
    cancel: "Cancel",
    back: "Back",
  },
  sidebar: {
    dashboard: "Dashboard",
    submitMatch: "Submit Match",
    matchHistory: "Match History",
    settings: "Settings",
    signOut: "Sign Out",
    signIn: "Sign In",
    proAccount: "Pro Account",
  },
  dashboard: {
    tacticalIntel: "Tactical Intel",
    loggedAs: "Logged as",
    newRoster: "NEW ROSTER",
    eliteCompetitor: "ELITE COMPETITOR",
    dominateCourt: "Dominate the Court",
    smashLimits: "Smash the Limits",
    newRosterDesc: "Track every shuttlecock and analyze tactical patterns to climb the rankings.",
    eliteDesc: "Archived {count} matches with a professional {ratio}% win efficiency.",
    bestAlly: "Best Ally",
    frequent: "Frequent",
    nemesis: "Nemesis",
    favRival: "Fav Rival",
    timelineAction: "Timeline Action",
    viewAll: "View All",
    victoryMetrics: "Victory Metrics",
    sessions: "Sessions",
    efficiency: "Efficiency",
    victories: "Victories",
    defeats: "Defeats",
    featurePrecision: "Precision Tracking",
    featurePrecisionDesc: "Log every point to visualize your elite consistency and tactical growth.",
    featureGrouping: "Event Grouping",
    featureGroupingDesc: "Group matches by tournament to track your professional trajectory.",
    featureAnalytics: "Elite Analytics",
    featureAnalyticsDesc: "Unlock tactical trends and automated visualizations for your game.",
  },
  history: {
    historyTitle: "History",
    timeline: "Timeline",
    groups: "Groups",
    tacticalFilters: "Tactical Filters",
    roster: "Roster",
    event: "Event",
    allPlayers: "All Players",
    allEvents: "All Events",
    resetTactical: "Reset Tactical",
    noMatchData: "No match data found.",
    clearFilters: "Clear Tactical Filters",
    tacticalHistory: "Tactical History",
    tacticalDeBrief: "Tactical De-brief",
    fullArchivalMatch: "Full Archival Match Analysis",
    teamAlpha: "Team Alpha (Elite)",
    teamOmega: "Team Omega (Rivals)",
    teammate: "Teammate",
    rivalPartner: "Rival Partner",
    setPerformance: "Set Performance Center",
    arenaVenue: "Arena Venue",
    sessionDate: "Session Date",
    deBriefNotes: "Tactical De-brief Notes",
    noNotes: "No tactical notes were recorded for this session.",
    trainingPerformance: "Training Performance",
  },
  matchForm: {
    recordAction: "Record Action",
    recordPerformance: "Record Performance",
    editPerformance: "Edit Performance",
    archiveSession: "Archive a professional tactical session",
    updateRecord: "Update tactical record data",
    tacticalDate: "Tactical Date",
    startTime: "Start Time",
    format: "Format",
    tournament: "Tournament (Optional)",
    leaveEmptyTraining: "Leave empty for Training",
    arenaVenue: "Arena Venue",
    location: "Location",
    finalResult: "Final Result",
    teamAlpha: "Team Alpha (You)",
    teamOmega: "Team Omega (Rivals)",
    partnerName: "Partner Name",
    rivalName: "Rival Name",
    rivalPartner: "Rival Partner",
    setScores: "Set Scores",
    deBriefPlaceholder: "Notes on strategy, physical state, or patterns...",
    rewriteArchive: "Rewrite Archive",
  },
  settings: {
    playerIdentity: "Player Identity",
    eliteProfile: "Elite Profile",
    manageRosterInfo: "Manage your tactical roster information",
    avatarSource: "Avatar Source URL",
    avatarPlaceholder: "Global image URL...",
    firstName: "First Name",
    lastName: "Last Name",
    rosterUsername: "Roster Username",
    updateIdentity: "Update Identity",
  },
  login: {
    eliteAnalytics: "Elite Badminton Analytics",
    signIn: "SIGN IN",
    joinRoster: "JOIN ROSTER",
    secureAccess: "SECURE ACCESS",
    emailIdentity: "Email Identity",
    securityKey: "Security Key",
    initializeProfile: "Initialize Profile",
    accessDashboard: "Access Dashboard",
    continueWithGoogle: "Continue with Google",
    keysError: "Security keys must be at least 6 characters.",
    authFailed: "Authorization failed. Verify credentials.",
  }
};
